### ISSUE TITLE
Fix problems detected by opam CI

### ISSUE THREAD

**Issue by andersfugmann** [andersfugmann/ocaml-protoc-plugin#28]
```[tasklist]
### Tasks
- [x] 32 bit platform failed on large integers
- [x] Linking failed on `std::filesystem`
- [x] Linking failed on freebsd. Should use `pkg-config` to determine location of `libprotobuf.so`
```

### 32 bit platform failed on large integers:
```
File "src/ocaml_protoc_plugin/serialize_json.ml", line 122, characters 7-17:
# 122 |   test 1709931283 0;
````
Consider using Int64.t for tests and decoding/encoding

### Linking failed on `std::filesystem`
```
 protobuf2json.cc:47:34: error: 'std::filesystem' has not been declared
         for(const auto& p : std::filesystem::directory_iterator(".")) {
```
and 
```
# protobuf2json.cc:15:10: fatal error: filesystem: No such file or directory
#  #include <filesystem>
```

Consider removing this test code as its unused 

 ### Linking failed on freebsd
```
# ld: error: unable to find library -lprotobuf
```

Understand what the library is called on freebsd, or allow ci-failures on freebsd

**Comment by andersfugmann** [comment]
First two resolved. The linker error on freebsd is strange, as it used to work.
the package on freebsd is [protobuf](https://freebsd.pkgs.org/14/freebsd-amd64/protobuf-24.4,1.pkg.html), and it provides `libprotobuf.so`, so linking against it should work.

**Comment by andersfugmann** [comment]
Ah. When linking, we should use pkg-config to find the correct link flags and not hardcode it

**Comment by andersfugmann** [comment]
All issues believed to be resolved. Closing
